import { createEditor } from '../src/workbook/engine'
import { markCircularFormulas } from '../src/workbook/formulaValidation'
import { fromUniver, newId, toUniver, countCells, type Snapshot } from '../src/workbook/adapter'
const ids = new Map<string,string>()
const snapshot: Snapshot = {schema_version:1,id:newId(),name:'完整编辑验收',date1904:false,sheets:[{id:newId(),name:'数据',row_count:100,column_count:26,cells:{},rows:{},columns:{},merges:[],freeze:{row:0,column:0},filter:null}]}
const engine=createEditor(document.getElementById('editor')!,toUniver(snapshot))
const check=(condition:unknown,message:string)=>{if(!condition)throw new Error(message)}
async function run() {
  await new Promise<void>(resolve=>engine.api.getHooks().onReady(()=>resolve()))
  const s=engine.workbook.getActiveSheet()
  s.getRange('A1:C3').setValues([['名称','数量','金额'],['甲',2,10],['乙',4,20]])
  s.getRange('B2').setValue(9)
  await engine.api.undo();check(s.getRange('B2').getValue()===2,'undo')
  await engine.api.redo();check(s.getRange('B2').getValue()===9,'redo')
  s.getRange('A1:C1').setFontWeight('bold').setFontStyle('italic').setFontFamily('宋体').setFontSize(14).setBackgroundColor('#AABBCC').setHorizontalAlignment('center')
  s.getRange('C2:C3').setNumberFormat('¥#,##0.00')
  s.getRange('E2').setValue(.125).setNumberFormat('0.0%')
  s.getRange('A5:C5').merge();s.getRange('A5').setValue('合并文本')
  s.setColumnWidth(0,150);s.setRowHeight(0,38);s.hideRows(6,1);s.setFrozenRows(1);s.setFrozenColumns(1)
  s.insertRows(3,1);s.deleteRows(3,1)
  const added=engine.workbook.create('明细',100,26);added.getRange('A1').setValue(5);added.setName('其他')
  s.getRange('F1').setFormula('=SUM(C2:C3)+其他!A1')
  engine.api.getFormula().executeCalculation();await engine.api.getFormula().onCalculationResultApplied(30000)
  check(s.getRange('F1').getValue()===35,'cross sheet formula after sheet creation')
  const filter=s.getRange('A1:C3').createFilter();check(!!filter,'filter creation')
  filter!.setColumnFilterCriteria(0,{colId:0,filters:{filters:['甲']}})
  const raw=engine.workbook.save(), normalized=fromUniver(raw,snapshot,ids,(sid,r,c)=>engine.workbook.getSheetBySheetId(sid)!.getRange(r,c).getFormula())
  const first=normalized.sheets[0]
  check(first.cells['1,2'].style?.num_format==='¥#,##0.00','currency roundtrip')
  check(first.cells['1,4'].style?.num_format==='0.0%','percentage roundtrip')
  check(first.cells['0,0'].style?.bold && first.cells['0,0'].style?.italic,'font styles')
  check(first.merges.length===1 && first.freeze.row===1 && first.freeze.column===1,'merge/freeze')
  check(first.rows['6'].hidden && first.columns['0'].width===150,'dimensions')
  check(first.filter?.range.r1===2,'filter snapshot')
  check(first.filter?.hidden_rows.includes(2),'filtered rows retained')
  // Column common formatting must not allocate a cell for every empty row.
  engine.workbook.setActiveSheet(s)
  const before=countCells(normalized)
  await engine.api.executeCommand('sheet.command.set-style',{range:{startRow:0,endRow:99,startColumn:10,endColumn:10,rangeType:2},style:{type:'bl',value:1}})
  const common=fromUniver(engine.workbook.save(),snapshot,ids)
  check(countCells(common)===before,'column style must stay sparse')
  check(common.sheets[0].columns['10'].style?.bold,'column common style preserved')
  await engine.api.undo();check(!fromUniver(engine.workbook.save(),snapshot,ids).sheets[0].columns['10']?.style?.bold,'column style undo')
  await engine.api.redo()
  const wholeColumn=s.getRange('K:K')
  wholeColumn.getRange().rangeType=2
  s.setActiveRange(wholeColumn)
  s.getRange('K:K').setNumberFormat('0.00%')
  const formatted=fromUniver(engine.workbook.save(),snapshot,ids)
  check(countCells(formatted)===before,'column number format must stay sparse')
  check(formatted.sheets[0].columns['10'].style?.num_format==='0.00%','column common number format retained')
  filter!.remove()
  await engine.api.executeCommand('sheet.command.sort-range',{unitId:engine.workbook.getId(),subUnitId:s.getSheetId(),range:{startRow:1,endRow:2,startColumn:0,endColumn:2},orderRules:[{colIndex:1,type:'asc'}],hasTitle:false})
  check(s.getRange('B2').getValue()===4 && s.getRange('B3').getValue()===9,'sort records')
  const count=engine.workbook.getNumSheets();engine.workbook.moveSheet(added,0)
  check(engine.workbook.save().sheetOrder[0]===added.getSheetId(),'sheet order')
  engine.workbook.moveSheet(added,1)
  const temporary=engine.workbook.create('可删除',20,20);engine.workbook.setActiveSheet(temporary);engine.workbook.deleteActiveSheet()
  check(engine.workbook.getNumSheets()===count,'sheet deletion')
  engine.workbook.setActiveSheet(s)
  s.getRange('H1:H2').setValues([[1],[2]]);await s.getRange('H1:H2').autoFill(s.getRange('H1:H5'),'SERIES')
  check(s.getRange('H5').getValue()===5,'series fill')
  const invalid=engine.workbook.create('公式错误',100,26)
  invalid.getRange('A1:F1').setValues([['=1/0','=B1','=B1+1','=E1','=D1','=SUM(1,2)']])
  engine.api.getFormula().executeCalculation();await engine.api.getFormula().onCalculationResultApplied(30000)
  const analyzed=fromUniver(engine.workbook.save(),snapshot,ids)
  markCircularFormulas(analyzed,await engine.api.getFormula().getAllDependencyTrees(30000),ids)
  const errors=analyzed.sheets.find(sheet=>sheet.name==='公式错误')!
  check(errors.cells['0,0'].result_state==='error','division by zero must be an explicit error')
  for(const col of [1,2,3,4]) check(errors.cells[`0,${col}`].value==='#CYCLE!','cycle and its dependents must be explicit errors')
  check(errors.cells['0,5'].value===3 && errors.cells['0,5'].result_state==='ready','unrelated formula must remain valid')
  engine.workbook.deleteActiveSheet();engine.workbook.setActiveSheet(s)
  ;(window as any).engineResult={passed:true,snapshot:fromUniver(engine.workbook.save(),snapshot,ids),checks:['undo','redo','font','currency','percent','merge','freeze','row-column','sheet-create-rename-order-delete','formula','filter','sort','fill','sparse-column-style','sparse-column-number-format','formula-errors-and-cycle']}
}
run().catch(error=>{(window as any).engineResult={passed:false,error:String(error),stack:error.stack}})
