SELECT COUNT_BIG(*) AS [根BOM数量]
FROM dbo.T_ENG_BOM AS b
INNER JOIN dbo.T_BD_MATERIAL AS m
    ON m.FMATERIALID = b.FMATERIALID
WHERE m.FNUMBER = :MaterialNumber
  AND b.FNUMBER = :BomVersion
  AND b.FDOCUMENTSTATUS = 'C'
  AND b.FFORBIDSTATUS = 'A'
